### ISSUE TITLE
0.4.8 and 0.4.9 releases missing from git

### ISSUE THREAD

**Issue by evgeni** [OpenSCAP/ruby-openscap#17]
https://rubygems.org/gems/openscap lists 0.4.8 and 0.4.9 as being available,

but https://github.com/OpenSCAP/ruby-openscap/blob/master/lib/openscap/version.rb only shows 0.4.8 (via https://github.com/OpenSCAP/ruby-openscap/commit/735b1f80778072574f72de4cbdaa6b5ef5d86d99) and there is no tag for either version.

are the versions on rubygems legit and if so, can you please sync git with rubygems?

**Comment by isimluk** [comment]
I did not push 0.4.9 version to the rubygems. I always tag the upstream first.

**Comment by isimluk** [comment]
meh, based on the logs it seems I did. :man_shrugging:

**Comment by isimluk** [comment]
I have verified content of the 0.4.9 gem at rubygem.

I have verified content file by file there is nothing rogue in there.

Thank You for checking!

**Comment by evgeni** [comment]
Thanks! Can you please update Version.rb and tag it? :)

**Comment by evgeni** [comment]
Thanks a ton again!
