### ISSUE TITLE
test_session_new_bad fails under OpenSCAP 1.2.6

### ISSUE THREAD

**Issue by domcleal** [OpenSCAP/ruby-openscap#7]
The test_session_new_bad test, which tries to open a file with an empty string now fails under OpenSCAP 1.2.6 with a different error message to the one it expects:

<pre>
  1) Failure:
test_session_new_bad(TestSession) [/builddir/build/BUILD/openscap-0.4.3/test/xccdf/session_test.rb:24]:
Message was: Unable to open file: '' [oscap_source.c:220]
</pre>

In 1.2.5 the error returned from `OpenSCAP::Xccdf::Session.new('')` was `failed to load external entity "" [oscap_source.c:186] \n Unable to parse XML at: '' [oscap_source.c:187]`.

In 1.2.6 it's only `Unable to open file: '' [oscap_source.c:220]`.

**Comment by isimluk** [comment]
Thanks Dominic for report.

We will set-up our CI to include this project as well.
